emacsorphanage/helm-ag

README.md
helm-ag.el

CC @vermiculus This is related to #45.

[WIP] Implement parent directory searching(#45)

---

.travis.yml
helm-ag.el

Support searching parent directory

---

README.md
helm-ag.el

Add flag for using grep ignore lists as ignore pattern

---

README.md
helm-ag.el
test/test-util.el

We can specify option by this change.

Improve input for #51

---

helm-ag.el

See https://github.com/syohex/emacs-helm-ag/issues/51#issuecomment-70316541

Dont use default value

---

helm-ag.el

Usually I don't want to search outside of repository.

Query whether searching continues

---

helm-ag.el

helm-do-ag works like helm-do-grep with C-u prefix

---

README.md
helm-ag.el

- Show search directory in helm header for `helm-do-ag`
- Generate error if input query is empty string
- Implement open other window(`C-c o`) feature

Improve something

---

README.md
helm-ag.el

Help command

---

helm-ag.el
test/test-util.el

See:
http://emacs.stackexchange.com/questions/9795/helm-projectile-ag-omitting-src-directory-in-project

Add ignore parameters which are passed to 'ag'

---

helm-ag.el

Initial implement saving buffer feature

---

helm-ag.el
test/test-util.el

Fix issue for query which has contains space

---

helm-ag.el
test/test-util.el

This fixes issue that searching is failed when query has dash.

Fix dash in query

---

helm-ag.el

Don't specified targets if candidate is only one and it is a directory

---

helm-ag.el

Set default directory when call up directory command

---

helm-ag.el

Support next-error and previous-error in edit buffer

---

helm-ag.el

We should set default directory before get-buffer-create.

Set default directory for saving buffer

---

helm-ag.el

kill saved buffer if it is still alive

---

README.md
helm-ag.el

Search buffers feature

---

helm-ag.el

Add save buffer action same as helm-do-grep

---

helm-ag.el

Apply 109 and some refactoring

---

helm-ag.el

I revised some strings for grammar/clarity.
Thanks for the very useful package!

Clarifying prompt/error messages

---

helm-ag.el

Implement helm-do-ag-this-file

---

helm-ag.el

This means support '-g' option.
This is related to #124.

Support case when only file names are displayed

---

helm-ag.el

Implement searching multiple directories feature

---

helm-ag.el
test/test-util.el

This is same as #128 except some refactoring.

Implement #128 feature

---

helm-ag.el

If helm-ag-use-agignore is non-nil, and project has '.agignore' file,
then helm-ag sets it '-p'(--path-to-agignore) option.
This is related to #98.

Add flag for using .agignore at project root

---

helm-ag.el

Set last-query in helm-do-ag

---

helm-ag.el

Fix for tramp

---

README.md

helm-projectile provides helm-projectile-ag which uses helm-do-ag.

Please use helm-projectile-ag

---

README.md
helm-ag.el

Add flag for not opening file in persistent action

---

helm-ag.el

Improve for using helm-do-ag-source from other commands

---

helm-ag.el

Accept ag command line option for helm-do-ag

---

helm-ag.el

Remove needless source

---

helm-ag.el

Implement updating saved buffer feature

---

README.md
helm-ag.el

Support delete line feature

---

helm-ag.el

Enable helm-follow-mode when helm-follow-mode-persistent is non-nil

---

helm-ag.el

Support context option(-A, -B, -C) output

---

README.md

This is related to #221.
CC: @triklsbg

Add tip about searching meta character literal

---

helm-ag.el

See https://github.com/syohex/emacs-helm-ag/issues/220#issuecomment-202325495
CC: @user471

Remove carriage returns on Windows

---

helm-ag.el

- Remove duplicated function
- Fix function definition position

Fix byte-compile warning

---

helm-ag.el

And refactoring code of exiting from edit mode.

Don't restore window if it is already killed

---

helm-ag.el

Show 'finished' in mode-line when ag completes

---

helm-ag.el

This is useful for custom mode-line packages like powerline, spaceline.
This is related to #232.
@TheBB How about this ?

Add customize variable for updating mode-line

---

helm-ag.el

This is related to #236.
CC: @blaenk

Set default input same as 'helm-ag'

---

helm-ag.el

This is related to #238.
CC: @dvzubarev

Fix keymap setting when commands are called from helm-resume

---

helm-ag.el

See
- https://github.com/syohex/emacs-helm-ag/issues/236#issuecomment-225080214
CC: @blaenk

Deactive mark when region is used as query

---

helm-ag.el

This is related to #249.
CC: @toupeira

Add edit results action

---

helm-ag.el

helm no longer supports Emacs 24.3.

Update minimum Emacs version

---

README.md
helm-ag.el
test/test-util.el

This is related to #269.
CC: @mmcnl

Add ignore pattern variable for buffer search commands

---

.travis.yml
README.md

Add ripgrep configuration

---

helm-ag.el
test/test-util.el

- Add test
- Refactoring code
This is related to #278.
CC: @agriffis

Improve 278 pull request

---

helm-ag.el

This implement #284 request.
CC: @yuandaxing

Enable helm query history

---

helm-ag.el

Added an optional parameter to supply default search term in helm-do-ag function.

Added optional default search term in helm-do-ag.

---

helm-ag.el

Patch source: https://github.com/emacsorphanage/helm-ag/issues/305#issuecomment-622924494
Allows results to be colored immediately as they are displayed, instead
of coloring being applied after all results are found which can take a
while when searching large directories.
---
I've only tested these changes myself for a few minutes, but they seem to work, and haven't caused any issues for me. Obviously I'm not the author of the code, just found it useful enough to put together a PR, so please let me know if something is not right or needs changing :)
/cc @syohex

Add syohex's patch for incremental coloring

---

helm-ag.el

Fix not appending grep option issue

---

helm-ag.el
test/test-util.el

As #309 is something I need, and it hasn't seen much movement, I figured I'd try my hand at applying the changes @syohex [suggested](https://github.com/emacsorphanage/helm-ag/pull/309#issuecomment-605090569) so we can get a PR together that might get merged soon.
Personally it seems to work when using ripgrep and doing fancy queries, but I'm not at all familiar with the code, as I didn't write any of it. Hence I can just give it a "seems to work on my machine" seal of approval, and leave it up to others who know more to vet this properly :)

Fix ripgrep highlighting (#309)

---

helm-ag.el

Fix searching parent directory issue

---

helm-ag.el

Show candidate if it does not looks like grep line

---

helm-ag.el

This was introduced by #339.
https://github.com/emacsorphanage/helm-ag/issues/218#issuecomment-692311439

Fix edit issue
