emacsorphanage/helm-ag

helm-ag.el
test/test-util.el

- improve performance for highlighting candidates
- improve highlighting candidates by converting from PCRE to Emacs Lisp regexp
- improve and fix bug of zero width matching such as '^'
This is very simple conversion
Here is a screenshot with pattern `(setq|string)`.
In this case, `helm-ag` converts from it to `\(setq\|string\)`

Improve regexp stuff

---

README.md
helm-ag.el
test/test-util.el

`ag` can take PCRE as pattern, while helm can take Emacs Lisp regexp.
This is confusing. So I implement simple converter Emacs Lisp regexp -> PCRE.
We can use Emacs Lisp regexp as pattern with this patch.

[WIP] Implement converter which converts emacs lisp regexp to PCRE

---

helm-ag.el

This is related to #99.
'pt' process is killed just after 'start-process' if path arguments
are not specified on Windows.
I confirmed that `helm-do-ag` works well on Window.

Fix for Windows pt

---

helm-ag.el
test/test-util.el

This make highlighting space meta characters correctly.

Convert space meta

---

README.md
helm-ag.el
test/test-util.el

Because `ag` uses smartcase matching as default.

Better highlighting

---

helm-ag.el

Related issue
- https://github.com/bbatsov/projectile/issues/819

Don't ask searched extensions when basedir is defined

---

helm-ag.el

default-directory must be set when calling file-relative-name.
This is related to #147.

Fix invalid target issue

---

helm-ag.el

Hi Syohei,
This PR allows to use `C-u` even when `basedir` is specified. I tested it and it seems to work but there might be a reason why this test was in place.
Cheers,
syl20bnr

helm-do-ag: Allow C-u with a provided basedir

---

helm-ag.el

helm-do-ag does not work on Windows because file names and line numbers
are not displayed. We can avoid this issue by '--vimgrep' option.

Change default option for Windows

---

helm-ag.el

font-lock-ensure is defined only development version.

Fix for older Emacs

---

helm-ag.el

We can input invert match pattern in PCRE like '^(?!.*pattern).+$'.
However it is difficult to type it. And this conversion is same as
normal helm command so that I suppose it is useful for helm users.
This is related to #187.
CC: @mpollmeier

Convert '!pattern' into invert match patter

---

README.md
helm-ag.el

This is related to #191.
CC: @env0der

Use own result buffer name if prefix-key is specified

---

helm-ag.el

`ag` sometimes doesn't have any output, if there are no hits for the given regular expression. I have `debug-on-error` set to t sometimes and don't like going to `*backtrace*`, since this isn't really an error. This turns that off.

don't try to debug errors caused by no ag output

---

README.md
helm-ag.el

This is similar to #199.
- Simple implementation
- Remove duplicated code
- No byte-compile warnings

Implementing moving file commands

---

helm-ag.el

`helm-ag-use-emacs-lisp-regexp` turns emacs lisp regexes into ag regexes when sending its results to ag; however, it doesn't do this when using `helm-do-ag`. This fixes that.

use elisp to pcre in searching with helm-do-ag

---

helm-ag.el

- Remove unused function
- Remove needless attribute
- Use `#'` instead of `'` for detecting typo

Refactoring code

---

helm-ag.el

ag does not show file name at one file searching while pt always shows
file name if only one file is matched.
This is related to #209.
CC: @gabrielsimoes

Fix this command issue with pt

---

helm-ag.el

If keymap is set at compile time, keymap is not available if user does not
input anything.
This is related to #253.
CC: @yuandaxing

[Workaround] Set keymap at runtime for #253

---

helm-ag.el

Use short file name instead of full path in buffer search commands

---

helm-ag.el

helm-ag is not capable to find a project root for files in git-worktree. It looks for a .git directory but in a worktree there is a .git file.

Fixes project root discovery in git worktrees

---

.travis.yml
helm-ag.el
test/test-util.el

`-g` option with query causes error. So helm-ag should show result even if query is not specified with such options.
This is related to #266.
CC: @gjstein

Fix for '-g' option

---

helm-ag.el

Keymap in helm-resume does not work without this.
This is related to https://github.com/emacs-helm/helm/issues/1678#event-938908476
CC: @it3ration

Set keymap in source definitions

---

helm-ag.el

This allows proper use of `DEFAULT-VALUE`, so the user can call
`next-history-element` (bound by default to `M-n`) to search for the symbol at point.

Use `read-from-minibuffer`

---

README.md

This also adds a reference to #293 to explain the reason for using --vimgrep with ag on Windows.

Don't recommend --vimgrep for rg #293

---

helm-ag.el

Since the editing buffer as some read-only text, attempting to erase it resulted
in an error message.

Fix editing results when such an editing buffer already exists

---

helm-ag.el

In reference to #301, the first commit adds an optional `query` parameter to the `helm-do-ag` command. The second commit adds it to all other commands, although `helm-do-ag` is the main one I'm interested in.
I've been using wrappers around `helm-do-ag` with these changes, which search for predefined things like TODO markers and use-package blocks etc. and it has worked perfectly fine.

Add optional query parameter to helm-do-ag

---

helm-ag.el
test/test-util.el

This is a simple bugfix. The original function that splits the query into the query and the options will not work with multiple options if there is anything that is not an option before it (i.e. if you wanted to write a query, and then refine what files it's operating on afterwards.)
Here is an example of the fixed function and the old behaviour (fixed is the one prefixed `fixed`).
```
(print (fixed--parse-options-and-query "hello -g world -g"))
; (("-g" "-g") . "hello world")
(print (helm-ag--parse-options-and-query "hello -g world -g"))
; (("-g" "-g") . "helloworld")
(print (fixed--parse-options-and-query "hello -g -g"))
;; (("-g" "-g") . "hello")
(print (helm-ag--parse-options-and-query "hello -g -g"))
;; (("-g") . "hello-g")
```

Fix helm-ag bug for multiple command line options.

---

helm-ag.el

I found myself using this package (via `(projectile-helm-ag)`) a lot.
However, I very often have a need to search for symbols that start
with `-`. And I use `(thing-at-point)` method to get the string. Without
this commit this results in
```
Candidates function ‘helm-ag--do-ag-candidate-process’ should run a process
```
I decided to fix that by preppending the search term, being it a selected text
or `(thing-at-point)`, with `--` to follow what is in readme.
Run tests from the `test-util.el` - they all pass. Quickly skimming the file
I haven't seen anything targeted to `(helm-do-ag)` nor `(helm-do-ag--helm)`.

Add double dash for default searched things

---

helm-ag.el

Helm provides `helm-goto-char` and `helm-goto-line` as alternatives to `goto-char` and `goto-line` that expand folded entries (for `org-mode`, `outline-mode` and `outline-minor-mode`).
Solves #303

Use helm-goto-char to show match and reveal outlines

---

helm-ag.el

We can use `pcre` on `ripgrep` if `ripgrep` is built with `pcre2` feature flag and use `--pcre2` command line flag. Then we can use negate match feature(`!pattern`) of helm-ag as below.
```lisp
(setq helm-ag-base-command "rg --no-heading --pcre2 --color=never --vimgrep")
```

Check --pcre2 option for ripgrep

---

.travis.yml
README.md
helm-ag.el

Remove travis badge since it's obsoleted and pointed to old repository. Moreover, since Github support show status now by default, the badge is not needed anymore.
Also, since `emacs-24` is old (> 8 years) and continuously failing build, we should just upgrade to support from `emacs-25`.

travis: remove travis badge and update env to support from emacs-25

---

helm-ag.el

Original code does not highlight filename until helm-occur is loaded

Load helm-occur for using face

---

README.md
helm-ag.el

Grep, ripgrep, probably others will use an exit status of 2 if there
was output, but a non-fatal error was encountered (for example,
attempting to access a file).
See BurntSushi/ripgrep#1278 for the motivation behind this one.  I'm using helm-ag with ripgrep, and there's a corner-case on windows I'm encountering where certain inaccessible files are being searched, resulting in an error.  This means that there is the expected search output, but because ripgrep (now) respects grep exit-code behaviour it returns 2, and helm-ag therefore tells you there was no output.
I can `(setq helm-ag-base-command "rg --no-messages --smart-case --no-heading --line-number")` (the `--no-messages` argument means no "soft" error messages will be output, just the search results), but the exit status still …

Handle "partial success" exit codes

---

helm-ag.el

The `helm-ag--command-succeeded-p` use `listp` inside not work as expected:
```elisp
(let ((helm-ag-success-exit-status nil))
(helm-ag--command-succeeded-p nil 0))
;; => nil (expected t)
```
The `listp` should be replaced with `consp`:
```elisp
(listp nil)     ;; => t
(consp nil)     ;; => nil
```

Fix "Failed: ’XXX’" when helm-ag-success-exit-status is nil

---

helm-ag.el

This does not highlight search word
This is related to #360 (CC: @taquangtrung)

Fix helm-ag persistent action highlight issue

---

helm-ag.el

The PR allows us to mark candidates in `helm-ag`, which is the behavior before this change: [ Add syohex's patch for incremental coloring ](https://github.com/emacsorphanage/helm-ag/commit/29d633643d1bb324a7c578aafa2b9caac3070043)
Example use case:  mark candidates and then do `helm-ag-edit` on them.

Allow candidates marking

---

helm-ag.el

1. `C-- M-x helm-do-ag` (minus prefix)
2. Set extra argument like `-G\.md`
3. `M-x helm-do-ag` 
4.  This `helm-do-ag` does not set extra argument, but the option which was set previous invocation is specified

Clear extra option if it is not set

---

.travis.yml

As far as I know, EVM does not provide Emacs 27: https://github.com/rejeep/evm
This PR replaces the usage of EVM with Nix, using these instructions: https://github.com/purcell/nix-emacs-ci
I've successfully made these changes in git-link (https://github.com/sshaw/git-link/pull/74) and Helm (https://github.com/emacs-helm/helm/pull/2366).
As far as I know, `make test` should run exactly as before with these changes.
With this PR, Travis CI would cover Emacs 25.1-3, 26.1-3 and 27.1

Travis CI covers Emac 27 with Nix

---

helm-ag.el

```
helm-ag.el:303:1: Warning: Unused lexical argument ‘cmd’ Disable showing
Disable logging
```

Fix byte-compile warning

---

helm-ag.el

This restores two lines that were removed on May 6, 2020 via https://github.com/emacsorphanage/helm-ag/commit/29d633643d1bb324a7c578aafa2b9caac3070043 which I presume was accidental.  Lines 1114 and 1115 are the lines of interest.
The restored lines signal that the search is done so that this can be used to for example to add "(DONE)" string on mode line as detailed at https://github.com/syl20bnr/spacemacs/issues/14455.
@alexey0308 discovered that the May 6 change dropped the two lines being restored by this PR.

restored two lines removed earlier

---

README.md

This is a fix for https://github.com/emacsorphanage/helm-ag/issues/403
Without `--line-number` option, `helm-ag-edit` does not work because it's unable to parse the result of `rg`.

doc: fix wrong rg command
